### ISSUE TITLE
Ironbound chests removed by tnt blasts

### ISSUE THREAD

**Issue by jhcole** [FozLand/castle#1]
The ironbound chest and its contents lost when destroyed by TNT. Its expected that the iron bound chest would survive the same way a locked chest does.

**Comment by mootpoint** [comment]
locked chests survive by : on_blast = function() end can we tes this on dev and apply to travelnet's as well if it works?

**Comment by jhcole** [comment]
This works. I submitted a pull request to upstream with the fix minetest-mods/castle#29. Lets definitely try the same thing for travelnets.

**Comment by mootpoint** [comment]
All right give me a second and it shall be done.
