### ISSUE TITLE
Doors are not mesecons operable

### ISSUE THREAD

**Issue by jhcole** [FozLand/castle#2]

**Comment by jhcole** [comment]
I remember discussing this, but I can't remember what we decided. I marked the doors in dev with bones but I forgot what that was supposed to mean.

@mootpoint do you think the castle doors should be operable by mesecons? They are both normally locked, like the steel door which is mesecon operable.  Either way, I put a patch in the doors branch and will merge (or not) based on discussion.

**Comment by jhcole** [comment]
I moved the code to Fozland/fozland so it can handle all the doors in one place.

**Comment by mootpoint** [comment]
Iirc , we decided to make them margin operable, but at the time the code was to long to add for those doors. Jieja said he would not as a global meseconify doors, but he asked sofar to include it in the doors mod. Have not heard anything else lately
